version: '3.8'

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'

  postgres:
    image:  'postgres:latest'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass123

  redis:
    image: 'redis:latest'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules #Inside the container don't touch this folder. Leave it as it is
      - ./server:/app #Everytime our application is trying to access anything inside the container in the "/app" directory it will look at the "./src" folder outside
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=root
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=pass123
      - PGPORT=5432

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379