name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - name : Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: docker build -t jochri3/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true jochri3/react-test npm test

      - run: docker build -t jochri3/multi-client ./client
      - run: docker build -t jochri3/multi-nginx ./nginx
      - run: docker build -t jochri3/multi-server ./server
      - run: docker build -t jochri3/multi-worker ./worker

      - run: docker push jochri3/multi-client
      - run: docker push jochri3/multi-nginx
      - run: docker push jochri3/multi-server
      - run: docker push jochri3/multi-worker
#
#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: multi-gh
#          environment_name: Multigh-env
#          existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
#          region: us-east-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip